apiVersion: apps/v1
kind: Deployment
metadata:
  name: portcheck
spec:
  selector:
    matchLabels:
      app: portcheck
  replicas: 1 
  template: 
    metadata:
      labels:
        app: portcheck
    spec:
      containers:
      - name: portcheck
        image: dipeshthakur/apps:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: portcheck
spec:
 type: NodePort
 selector:
   app: portcheck
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: portcheck
